version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 22
    commands:
      - composer install --ignore-platform-reqs
      - npm install
  pre_build:
    commands:
      - chmod +x ./scripts/env-build-generate.sh
      - ./scripts/env-build-generate.sh
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - rm -f .env
artifacts:
  files:
    - "**/*"
