global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: yinyang
    metrics_path: /metrics
    authorization:
      credentials: secret-token
    static_configs:
      - targets:
          - laravel:80
        labels:
          app: yinyang
